---
title: Spencer Tweedy
timezone: America/Chicago
collections:
  newsletters:
    title: Newsletters
    output: true
    permalink: "/observations/newsletters/:title/"
  observations:
    title: Observations
    output: true
    permalink: "/observations/:title/"
  posts:
    title: Posts
    output: true
    layout: post
  releases:
    title: Releases
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: observations
  values:
    layout: obs-post
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
    image_caption: 
- scope:
    path: ''
    type: releases
  values:
    artist: ''
    year: ''
    color: ''
    listen: ''
    image: ''
    role: ''
    is_single: ''
    is_featured: ''
- scope:
    path: ''
    type: newsletters
  values:
    layout: obs-newsletter
collections_dir: content
email: spencer@penguinmail.com
description: Hi! I play drums.
author: Spencer Tweedy
url: https://spencertweedy.com
twitter: spencertweedy
facebook: spencertweedy
instagram: spencertweedy
obs_twitter: spencertweedy
obs_instagram: observationsinc
typekit: ejh7rbn
cover_photo_path: "/assets/bg.jpg"
cover_photo_credit:
- David Zoubek
- https://www.davidzoubek.com
cover_photo_caption: "A portrait of Spencer Tweedy playing drums by David Zoubek."
locale: Chicago, IL
github_repo: https://github.com/spencertweedy/spencertweedy.github.io
markdown: kramdown
permalink: "/:categories/:title/"
include:
- _redirects
exclude:
- README.md
jekyll_tidy:
  compress_html: false
obs-archives:
  enabled:
    - month
  layouts:
    month: obs-month
  permalinks:
    month: '/archives/:year:month/'
