---
title: Spencer Tweedy
timezone: America/Chicago
collections:
  newsletters:
    title: Newsletters
    output: true
    permalink: "/observations/newsletters/:title:output_ext"
  posts:
    title: Posts
    output: true
    layout: post
  releases:
    title: Releases
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image:
    image_caption:
- scope:
    path: ''
    type: releases
  values:
    artist: ''
    year: ''
    color: ''
    listen: ''
    image: ''
    role: ''
    is_single: ''
    is_featured: ''
- scope:
    path: ''
    type: newsletters
  values:
    layout: obs-newsletter
email: spencer@penguinmail.com
description: Hi! I play drums.
author: Spencer Tweedy
baseurl:
url: https://spencertweedy.com
twitter: spencertweedy
facebook: spencertweedy
instagram: spencertweedy
buttondown: spencer
typekit: ejh7rbn
cover_photo_path: "/assets/bg.jpg"
cover_photo_credit:
- David Zoubek
- https://www.davidzoubek.com
locale: Chicago, IL
github_repo: https://github.com/spencertweedy/spencertweedy.github.io
markdown: kramdown
permalink: none
include:
  - _redirects
