# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spencer Tweedy
email: spencer@spencertweedy.com
description: >
  I play drums and work on music projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spencertweedy.com" # the base hostname & protocol for your site
timezone: America/Chicago

# Content variables
twitter: "spencertweedy"
facebook: "spencertweedy"
tinyletter: "spencertweedy"
typekit: ejh7rbn
cover_photo_path: '/assets/bg.jpg'
cover_photo_credit: ["David Zoubek","http://www.davidzoubek.com"]
locale: "Chicago, IL"
github_repo: "https://github.com/spencertweedy/spencertweedy.github.io"
google_analytics: "UA-15153122-1"

# Collection settings
collections:
- longhand_posts

collections:
  redirects:
    output: true
  longhand_posts:
    output: true
    layout: post

# Build settings
markdown: kramdown
gems:
  - jekyll-redirect-from
