---
title: Spencer Tweedy
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
    layout: post
  redirects:
    title: Redirects
    output: true
  releases:
    title: Releases
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: 
- scope:
    path: ''
    type: releases
  values:
    artist: ''
    year: ''
    color: ''
    listen: ''
    image: ''
    role: ''
    is_single: ''
    is_featured: ''
email: spencer@spencertweedy.com
description: I play drums and work on music projects.
author: Spencer Tweedy
baseurl: 
url: https://spencertweedy.com
twitter: spencertweedy
facebook: spencertweedy
tinyletter: spencertweedy
typekit: ejh7rbn
cover_photo_path: "/assets/bg.jpg"
cover_photo_credit:
- David Zoubek
- https://www.davidzoubek.com
locale: Chicago, IL
github_repo: https://github.com/spencertweedy/spencertweedy.github.io
quantcast: p-P2am1-BU2Leay
markdown: kramdown
permalink: none
plugins:
- jekyll-redirect-from
