---
title: Spencer Tweedy
timezone: America/Chicago
collections:
  longhand_posts:
    title: Longhand Posts
    output: true
    layout: longhand
  observations:
    title: Observations
    output: true
  posts:
    title: Posts
    output: true
    layout: post
  redirects:
    title: Redirects
    output: true
  releases:
    title: Releases
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: releases
  values:
    artist: ''
    year: ''
    color: ''
    listen: ''
    image: ''
    role: ''
    is_featured: ''
email: spencer@spencertweedy.com
description: I play drums and work on music projects.
baseurl: ''
url: http://spencertweedy.com
twitter: spencertweedy
facebook: spencertweedy
tinyletter: spencertweedy
typekit: ejh7rbn
cover_photo_path: "/assets/bg.jpg"
cover_photo_credit:
- David Zoubek
- http://www.davidzoubek.com
locale: Chicago, IL
github_repo: https://github.com/spencertweedy/spencertweedy.github.io
google_analytics: UA-15153122-1
markdown: kramdown
gems:
- jekyll-redirect-from
