# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spencer Tweedy
email: spencer@spencertweedy.com
description: > # this means to ignore newlines until "baseurl:"
  I play drums and work on music projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spencertweedy.com" # the base hostname & protocol for your site

phone: "(773) 888 4152"
twitter: "spencertweedy"
facebook: "spencertweedy"
tinyletter: ""

typekit: ""

cover_photo_path: ""
cover_photo_credit: ""

# Build settings
markdown: kramdown
