[build]
	command = "npm run build" # Tell Netlify what command to use to build the site
	publish = "_site" # Tell Netlify where the publishable build resides
	environment = { NODE_VERSION = "18.12.1" }

# If skip_processing = true, all other settings are ignored
[build.processing]
	skip_processing = false
[build.processing.html]
	pretty_urls = false
[build.processing.css]
	bundle = false
	minify = false
[build.processing.js]
	bundle = true
	minify = false
