backend:
  name: git-gateway
media_folder: "content/_uploads" # Tells Netlify CMS where to read/write uploads in the source folder
public_folder: "/uploads" # Tells Netlify CMS where to read uploads in the ouput folder
display_url: "https://spencertweedy.com" # Used in the UI
# Define collections (must manually keep up-to-date with site generator config)
collections:
  - name: "observations" # Used in routes, e.g., /admin/collections/blog
    label: "Observations" # Used in the UI
    label_singular: "Observations Post" # Used in the UI
    folder: "content/_observations" # The path to the folder where the documents are stored
    editor:
      preview: false # Because Netlify CMS has poor Liquid support
    create: true # Allow users to create new documents in this collection
    slug: "{{datestamp}}" # Observation post files that Netlify CMS creates will use the `datestamp` field as their slug
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "Observations YYYY-MM-DD"}
      - {label: "Datestamp", name: "datestamp", widget: "datetime", default: "", format: "YYYYMMDD", dateFormat: "LL", timeFormat: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Image caption", name: "image_caption", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "releases" # Used in routes, e.g., /admin/collections/blog
    label: "Releases" # Used in the UI
    label_singular: "Release" # Used in the UI
    folder: "content/_releases" # The path to the folder where the documents are stored
    editor:
      preview: false # Because Netlify CMS has poor Liquid support
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artist", name: "artist", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Color", name: "color", widget: "string"}
      - {label: "Listen URL", name: "listen", widget: "string", required: false}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Is it a single?", name: "is_single", widget: "boolean", default: false}
      - {label: "Feature it?", name: "is_featured", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
  - name: "announcements"
    label: "Announcements" # Used in the UI
    label_singular: "Announcement" # Used in the UI
    folder: "content/_announcements" # The path to the folder where the documents are stored
    editor:
      preview: false # Because Netlify CMS has poor Liquid support
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Background Color", name: "background_color", widget: "string", required: false}
      - {label: "Text Color", name: "text_color", widget: "string", required: false}
      - {label: "Make visible?", name: "is_visible", widget: "boolean", default: true}
  - name: "newsletters" # Used in routes, e.g., /admin/collections/blog
    label: "Newsletters" # Used in the UI
    label_singular: "Newsletter" # Used in the UI
    folder: "content/_newsletters" # The path to the folder where the documents are stored
    editor:
      preview: false # Because Netlify CMS has poor Liquid support
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.slug}}" # Observation post files that Netlify CMS creates will use the `datestamp` field as their slug
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "MonthName Year"}
      - {label: "Slug", name: "slug", widget: "string", default: "YYYYMM"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
